### ISSUE TITLE
undefined method `__bson_dump__' for Sun, 07 Oct 2012:Date

### ISSUE THREAD

**Issue by meidan1984** [dzello/mongoid_alize#13]
Hi,

Thanks very much for your great idea and implementation of Alize!
I found a small problem, do you have time to look at this?

Given below models:

```
class ApplicationRecord
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Alize

  field :received_date, type: Date

  belongs_to :candidate

  alize :candidate
end
```

and

```
class Candidate
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Alize

  field :english_name, type: String

  has_many :application_records

  alize :application_records
end
```

When you update Candidate, you will see

```
NoMethodError (undefined method `__bson_dump__' for Sun, 07 Oct 2012:Date):
```

The Date should be the received_date in ApplicationRecord

Remove alize, everything works fine.

Environment:
- MongoDB 2.0.7
- ruby 1.9.3p194
- rails (3.2.8)
- mongoid (3.1.0 a1c77d7)
- mongoid_alize (0.4.0)
- moped (1.2.7)

**Comment by klaustherubythree** [comment]
I did this to fix it (an initializer file):
class DateTime
  def __bson_dump__(x,z)
    self.to_time.__bson_dump__(x, z)
  end
end

**Comment by klaustherubythree** [comment]
I did this to fix it (an initializer file):
`class DateTime
def bson_dump(x,z)
self.to_time.bson_dump(x, z)
end
end`

**Comment by klaustherubythree** [comment]
I did this to fix it (an initializer file with anyone name):

```
class DateTime
  def bson_dump(x,z)
    self.to_time.bson_dump(x, z)
  end
end
```
