### ISSUE TITLE
Mongoid 6, Rails 5.1

### ISSUE THREAD

**Issue by utiq** [dzello/mongoid_alize#53]
Is this library is still active?
I'm trying to migrate and I get this error:

`ArgumentError: Passing string to define a callback is not supported. See the `.set_callback` documentation to see supported values.`

Rails 5.1.4
Mongoid 6.2.1
Ruby 2.4.3

**Comment by dzello** [comment]
I'm not proactively updating it for new Rails / Mongoid versions but happy to accept a PR. There is a full test suite that should make it easier to spot the issue, happy to advise on how to get that running.

**Comment by dzello** [comment]
Should work now, thanks to @joe1chen for the PR!
